// Vaca - Visual Application Components Abstraction
// Copyright (c) 2005-2010 David Capello
//
// This file is distributed under the terms of the MIT license,
// please read LICENSE.txt for more information.

#pragma once

#include "VACA/Base.hpp"

#include <exception>

namespace Wg {

/**
   Exception generated from Vaca.

   Base class for every exception generated by Vaca objects.
*/
class VACA_DLL Exception : public std::exception {
    String m_message;
    std::string m_what;
    int m_errorCode{};

public:

    Exception();

    Exception(const String &message);

    ~Exception() noexcept override;

    [[nodiscard]] const char *what() const noexcept override;

    [[nodiscard]] virtual const String &getMessage() const noexcept;

    [[nodiscard]] int getErrorCode() const;

private:

    void initialize();

};

} // namespace Wg
