// Vaca - Visual Application Components Abstraction
// Copyright (c) 2005-2010 David Capello
//
// This file is distributed under the terms of the MIT license,
// please read LICENSE.txt for more information.

#pragma once

#include "VACA/Base.h"

#include "VACA/Anchor.h"
#include "VACA/AnchorLayout.h"
#include "VACA/Application.h"
// #include "VACA/BandedDockArea.h"
// #include "VACA/BasicDockArea.h"
#include "VACA/Bind.h"
#include "VACA/Bix.h"
#include "VACA/BoxConstraint.h"
#include "VACA/BoxLayout.h"
#include "VACA/Brush.h"
#include "VACA/Button.h"
#include "VACA/ButtonBase.h"
#include "VACA/CancelableEvent.h"
#include "VACA/CheckBox.h"
#include "VACA/ClientLayout.h"
#include "VACA/Clipboard.h"
#include "VACA/CloseEvent.h"
#include "VACA/Color.h"
#include "VACA/ColorDialog.h"
#include "VACA/ComboBox.h"
#include "VACA/Command.h"
#include "VACA/CommandEvent.h"
#include "VACA/CommonDialog.h"
#include "VACA/Component.h"
#include "VACA/ConditionVariable.h"
#include "VACA/Constraint.h"
#include "VACA/ConsumableEvent.h"
#include "VACA/Cursor.h"
#include "VACA/CustomButton.h"
#include "VACA/CustomLabel.h"
#include "VACA/DataGrid.h"
#include "VACA/Debug.h"
#include "VACA/Dialog.h"
// #include "VACA/DockArea.h"
// #include "VACA/DockBar.h"
// #include "VACA/DockFrame.h"
#include "VACA/DropFilesEvent.h"
#include "VACA/Enum.h"
#include "VACA/Event.h"
#include "VACA/Exception.h"
#include "VACA/FileDialog.h"
#include "VACA/FindFiles.h"
#include "VACA/FindTextDialog.h"
#include "VACA/FocusEvent.h"
#include "VACA/Font.h"
#include "VACA/FontDialog.h"
#include "VACA/Frame.h"
#include "VACA/GdiObject.h"
#include "VACA/Graphics.h"
#include "VACA/GraphicsPath.h"
#include "VACA/GroupBox.h"
#include "VACA/HttpRequest.h"
#include "VACA/Icon.h"
#include "VACA/Image.h"
#include "VACA/ImageList.h"
#include "VACA/KeyEvent.h"
#include "VACA/Keys.h"
#include "VACA/Label.h"
#include "VACA/Layout.h"
#include "VACA/LayoutEvent.h"
#include "VACA/LinkLabel.h"
#include "VACA/ListBox.h"
#include "VACA/ListColumn.h"
#include "VACA/ListItem.h"
#include "VACA/ListView.h"
#include "VACA/Mdi.h"
#include "VACA/Menu.h"
#include "VACA/MenuItemEvent.h"
#include "VACA/Message.h"
#include "VACA/MouseEvent.h"
#include "VACA/MsgBox.h"
#include "VACA/Mutex.h"
#include "VACA/NonCopyable.h"
#include "VACA/PaintEvent.h"
#include "VACA/ParseException.h"
#include "VACA/Pen.h"
#include "VACA/Point.h"
#include "VACA/PreferredSizeEvent.h"
#include "VACA/ProgressBar.h"
#include "VACA/RadioButton.h"
#include "VACA/ReBar.h"
#include "VACA/Rect.h"
#include "VACA/Referenceable.h"
#include "VACA/Region.h"
#include "VACA/Register.h"
#include "VACA/ResizeEvent.h"
#include "VACA/ResourceException.h"
#include "VACA/ResourceId.h"
#include "VACA/RichEdit.h"
#include "VACA/Scintilla.h"
#include "VACA/ScopedLock.h"
#include "VACA/ScrollEvent.h"
#include "VACA/ScrollInfo.h"
#include "VACA/ScrollableWidget.h"
#include "VACA/Separator.h"
#include "VACA/SetCursorEvent.h"
#include "VACA/SharedPtr.h"
#include "VACA/Signal.h"
#include "VACA/Size.h"
#include "VACA/Slider.h"
#include "VACA/Slot.h"
#include "VACA/SpinButton.h"
#include "VACA/Spinner.h"
#include "VACA/SplitBar.h"
#include "VACA/StatusBar.h"
#include "VACA/String.h"
#include "VACA/Style.h"
#include "VACA/System.h"
#include "VACA/Tab.h"
#include "VACA/TextEdit.h"
#include "VACA/Thread.h"
#include "VACA/TimePoint.h"
#include "VACA/Timer.h"
#include "VACA/ToggleButton.h"
#include "VACA/ToolBar.h"
#include "VACA/TreeNode.h"
#include "VACA/TreeView.h"
#include "VACA/TreeViewEvent.h"
#include "VACA/Widget.h"
#include "VACA/WidgetClass.h"
#include "VACA/WidgetHit.h"
#include "VACA/WidgetList.h"
