// Vaca - Visual Application Components Abstraction
// Copyright (c) 2005-2010 David Capello
//
// This file is distributed under the terms of the MIT license,
// please read LICENSE.txt for more information.

#pragma once

#include "VACA/Base.hpp"

#include "VACA/Anchor.hpp"
#include "VACA/AnchorLayout.hpp"
#include "VACA/Application.hpp"
// #include "VACA/BandedDockArea.h"
// #include "VACA/BasicDockArea.h"
#include "VACA/Bind.hpp"
#include "VACA/Bix.hpp"
#include "VACA/BoxConstraint.hpp"
#include "VACA/BoxLayout.hpp"
#include "VACA/Brush.hpp"
#include "VACA/Button.hpp"
#include "VACA/ButtonBase.hpp"
#include "VACA/CancelableEvent.hpp"
#include "VACA/CheckBox.hpp"
#include "VACA/ClientLayout.hpp"
#include "VACA/Clipboard.hpp"
#include "VACA/CloseEvent.hpp"
#include "VACA/Color.hpp"
#include "VACA/ColorDialog.hpp"
#include "VACA/ComboBox.hpp"
#include "VACA/Command.hpp"
#include "VACA/CommandEvent.hpp"
#include "VACA/CommonDialog.hpp"
#include "VACA/Component.hpp"
#include "VACA/ConditionVariable.hpp"
#include "VACA/Constraint.hpp"
#include "VACA/ConsumableEvent.hpp"
#include "VACA/Cursor.hpp"
#include "VACA/CustomButton.hpp"
#include "VACA/CustomLabel.hpp"
#include "VACA/DataGrid.hpp"
#include "VACA/Debug.hpp"
#include "VACA/Dialog.hpp"
// #include "VACA/DockArea.h"
// #include "VACA/DockBar.h"
// #include "VACA/DockFrame.h"
#include "VACA/DropFilesEvent.hpp"
#include "VACA/Enum.hpp"
#include "VACA/Event.hpp"
#include "VACA/Exception.hpp"
#include "VACA/FileDialog.hpp"
#include "VACA/FindFiles.hpp"
#include "VACA/FindTextDialog.hpp"
#include "VACA/FocusEvent.hpp"
#include "VACA/Font.hpp"
#include "VACA/FontDialog.hpp"
#include "VACA/Frame.hpp"
#include "VACA/GdiObject.hpp"
#include "VACA/Graphics.hpp"
#include "VACA/GraphicsPath.hpp"
#include "VACA/GroupBox.hpp"
#include "VACA/HttpRequest.hpp"
#include "VACA/Icon.hpp"
#include "VACA/Image.hpp"
#include "VACA/ImageList.hpp"
#include "VACA/KeyEvent.hpp"
#include "VACA/Keys.hpp"
#include "VACA/Label.hpp"
#include "VACA/Layout.hpp"
#include "VACA/LayoutEvent.hpp"
#include "VACA/LinkLabel.hpp"
#include "VACA/ListBox.hpp"
#include "VACA/ListColumn.hpp"
#include "VACA/ListItem.hpp"
#include "VACA/ListView.hpp"
#include "VACA/Mdi.hpp"
#include "VACA/Menu.hpp"
#include "VACA/MenuItemEvent.hpp"
#include "VACA/Message.hpp"
#include "VACA/MouseEvent.hpp"
#include "VACA/MsgBox.hpp"
#include "VACA/Mutex.hpp"
#include "VACA/NonCopyable.hpp"
#include "VACA/PaintEvent.hpp"
#include "VACA/ParseException.hpp"
#include "VACA/Pen.hpp"
#include "VACA/Point.hpp"
#include "VACA/PreferredSizeEvent.hpp"
#include "VACA/ProgressBar.hpp"
#include "VACA/RadioButton.hpp"
#include "VACA/ReBar.hpp"
#include "VACA/Rect.hpp"
#include "VACA/Referenceable.hpp"
#include "VACA/Region.hpp"
#include "VACA/Register.hpp"
#include "VACA/ResizeEvent.hpp"
#include "VACA/ResourceException.hpp"
#include "VACA/ResourceId.hpp"
#include "VACA/RichEdit.hpp"
#include "VACA/Scintilla.hpp"
#include "VACA/ScopedLock.hpp"
#include "VACA/ScrollEvent.hpp"
#include "VACA/ScrollInfo.hpp"
#include "VACA/ScrollableWidget.hpp"
#include "VACA/Separator.hpp"
#include "VACA/SetCursorEvent.hpp"
#include "VACA/SharedPtr.hpp"
#include "VACA/Signal.hpp"
#include "VACA/Size.hpp"
#include "VACA/Slider.hpp"
#include "VACA/Slot.hpp"
#include "VACA/SpinButton.hpp"
#include "VACA/Spinner.hpp"
#include "VACA/SplitBar.hpp"
#include "VACA/StatusBar.hpp"
#include "VACA/String.hpp"
#include "VACA/Style.hpp"
#include "VACA/System.hpp"
#include "VACA/Tab.hpp"
#include "VACA/TextEdit.hpp"
#include "VACA/Thread.hpp"
#include "VACA/TimePoint.hpp"
#include "VACA/Timer.hpp"
#include "VACA/ToggleButton.hpp"
#include "VACA/ToolBar.hpp"
#include "VACA/TreeNode.hpp"
#include "VACA/TreeView.hpp"
#include "VACA/TreeViewEvent.hpp"
#include "VACA/Widget.hpp"
#include "VACA/WidgetClass.hpp"
#include "VACA/WidgetHit.hpp"
#include "VACA/WidgetList.hpp"
