// Vaca - Visual Application Components Abstraction
// Copyright (c) 2005-2010 David Capello
//
// This file is distributed under the terms of the MIT license,
// please read LICENSE.txt for more information.

#pragma once

#include "Wg/Base.hpp"

#include "Wg/Anchor.hpp"
#include "Wg/AnchorLayout.hpp"
#include "Wg/Application.hpp"
// #include "Wg/BandedDockArea.h"
// #include "Wg/BasicDockArea.h"
#include "Wg/Bind.hpp"
#include "Wg/Bix.hpp"
#include "Wg/BoxConstraint.hpp"
#include "Wg/BoxLayout.hpp"
#include "Wg/Brush.hpp"
#include "Wg/Button.hpp"
#include "Wg/ButtonBase.hpp"
#include "Wg/CancelableEvent.hpp"
#include "Wg/CheckBox.hpp"
#include "Wg/ClientLayout.hpp"
#include "Wg/Clipboard.hpp"
#include "Wg/CloseEvent.hpp"
#include "Wg/Color.hpp"
#include "Wg/ColorDialog.hpp"
#include "Wg/ComboBox.hpp"
#include "Wg/Command.hpp"
#include "Wg/CommandEvent.hpp"
#include "Wg/CommonDialog.hpp"
#include "Wg/Component.hpp"
#include "Wg/ConditionVariable.hpp"
#include "Wg/Constraint.hpp"
#include "Wg/ConsumableEvent.hpp"
#include "Wg/Cursor.hpp"
#include "Wg/CustomButton.hpp"
#include "Wg/CustomLabel.hpp"
#include "Wg/DataGrid.hpp"
#include "Wg/Debug.hpp"
#include "Wg/Dialog.hpp"
// #include "Wg/DockArea.h"
// #include "Wg/DockBar.h"
// #include "Wg/DockFrame.h"
#include "Wg/DropFilesEvent.hpp"
#include "Wg/Enum.hpp"
#include "Wg/Event.hpp"
#include "Wg/Exception.hpp"
#include "Wg/FileDialog.hpp"
#include "Wg/FindFiles.hpp"
#include "Wg/FindTextDialog.hpp"
#include "Wg/FocusEvent.hpp"
#include "Wg/Font.hpp"
#include "Wg/FontDialog.hpp"
#include "Wg/Frame.hpp"
#include "Wg/GdiObject.hpp"
#include "Wg/Graphics.hpp"
#include "Wg/GraphicsPath.hpp"
#include "Wg/GroupBox.hpp"
#include "Wg/HttpRequest.hpp"
#include "Wg/Icon.hpp"
#include "Wg/Image.hpp"
#include "Wg/ImageList.hpp"
#include "Wg/KeyEvent.hpp"
#include "Wg/Keys.hpp"
#include "Wg/Label.hpp"
#include "Wg/Layout.hpp"
#include "Wg/LayoutEvent.hpp"
#include "Wg/LinkLabel.hpp"
#include "Wg/ListBox.hpp"
#include "Wg/ListColumn.hpp"
#include "Wg/ListItem.hpp"
#include "Wg/ListView.hpp"
#include "Wg/Mdi.hpp"
#include "Wg/Menu.hpp"
#include "Wg/MenuItemEvent.hpp"
#include "Wg/Message.hpp"
#include "Wg/MouseEvent.hpp"
#include "Wg/MsgBox.hpp"
#include "Wg/Mutex.hpp"
#include "Wg/NonCopyable.hpp"
#include "Wg/PaintEvent.hpp"
#include "Wg/ParseException.hpp"
#include "Wg/Pen.hpp"
#include "Wg/Point.hpp"
#include "Wg/PreferredSizeEvent.hpp"
#include "Wg/ProgressBar.hpp"
#include "Wg/RadioButton.hpp"
#include "Wg/ReBar.hpp"
#include "Wg/Rect.hpp"
#include "Wg/Referenceable.hpp"
#include "Wg/Region.hpp"
#include "Wg/Register.hpp"
#include "Wg/ResizeEvent.hpp"
#include "Wg/ResourceException.hpp"
#include "Wg/ResourceId.hpp"
#include "Wg/RichEdit.hpp"
#include "Wg/Scintilla.hpp"
#include "Wg/ScopedLock.hpp"
#include "Wg/ScrollEvent.hpp"
#include "Wg/ScrollInfo.hpp"
#include "Wg/ScrollableWidget.hpp"
#include "Wg/Separator.hpp"
#include "Wg/SetCursorEvent.hpp"
#include "Wg/SharedPtr.hpp"
#include "Wg/Signal.hpp"
#include "Wg/Size.hpp"
#include "Wg/Slider.hpp"
#include "Wg/Slot.hpp"
#include "Wg/SpinButton.hpp"
#include "Wg/Spinner.hpp"
#include "Wg/SplitBar.hpp"
#include "Wg/StatusBar.hpp"
#include "Wg/String.hpp"
#include "Wg/Style.hpp"
#include "Wg/System.hpp"
#include "Wg/Tab.hpp"
#include "Wg/TextEdit.hpp"
#include "Wg/Thread.hpp"
#include "Wg/TimePoint.hpp"
#include "Wg/Timer.hpp"
#include "Wg/ToggleButton.hpp"
#include "Wg/ToolBar.hpp"
#include "Wg/TreeNode.hpp"
#include "Wg/TreeView.hpp"
#include "Wg/TreeViewEvent.hpp"
#include "Wg/Widget.hpp"
#include "Wg/WidgetClass.hpp"
#include "Wg/WidgetHit.hpp"
#include "Wg/WidgetList.hpp"
